name: dart_cli_tools_demo
description: A sample command-line application.
# version: 1.0.0
# homepage: https://github.com/kenreilly/dart-cli-tools-demo
# author: Kenneth Reilly <kenneth@innovationgroup.tech>

environment:
  sdk: '>=2.1.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
